### ISSUE TITLE
Use without server

### ISSUE THREAD

**Issue by smoooty** [mattdiamond/Recorderjs#104]
I'm wondering why this cannot be used without a server or maybe there is a way that it can be? The issue puzzles me because in my experience web audio will function fine in this environment.

**Comment by kmturley** [comment]
You don't need a server to use this script? only if you want to save the files afterwards?

**Comment by b-d-b** [comment]
You have to serve it from a simple HTTP server at the very least because that's the only way to get a request for the browser audio context. @kmturley 

You have to have access to the audio context in the browser and I think that requires receiving the file from HTTP/HTTPS.  In chrome it won't work any other way.  I haven't tested it anywhere else though.

**Comment by kmturley** [comment]
ah yeah you are right, I didn't realise audio context required http. I have used it inside Cordova without any problems, but it must be setting a flag:
http://stackoverflow.com/questions/13723699/chrome-getusermedia-not-requesting-permission-locally

**Comment by b-d-b** [comment]
Thanks for the link, didn't know you could set flags like that.  Handy.
